bh_homepage:
    path:     /
    defaults: { _controller: BhBundle:Default:index }

BhBundle_api:
    resource: "@BhBundle/Resources/config/routing/api.yml"
    prefix:   /api

BhBundle_phone:
    resource: "@BhBundle/Resources/config/routing/phone.yml"
    prefix:   /phone

