services:
    bh.request_listener:
        class: Bh\Bundle\Services\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onException, priority: 255 }

