services:
    bh.request_listener:
        class: Bh\Bundle\Services\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onException, priority: 255 }

    bh.email:
        class: Bh\Bundle\Services\EmailService
        arguments:
            - %sendgrid_user%
            - %sendgrid_pass%

    bh.donate:
        class: Bh\Bundle\Services\DonateService
        arguments:
            - %braintree_merchant%
            - %braintree_public%
            - %braintree_private%

    bh.phone:
        class: Bh\Bundle\Services\PhoneService
        arguments:
            - %twilio_id%
            - %twilio_token%
            - %twilio_number%

